# Name of your application. Used to uniquely configure containers.
service: crm

# Name of the container image.
image: crm

# Deploy to these servers.
servers:
  web:
    hosts:
      - 52.30.167.17
    options:
      network-alias: crm-web

# Enable SSL auto certification via Let's Encrypt.
# Requires config.assume_ssl and config.force_ssl in production.rb
proxy:
  ssl: true
  host: mercuriocrm.es

# AWS ECR Registry
registry:
  server: 225656797743.dkr.ecr.eu-west-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - ANTHROPIC_API_KEY
    - MICROSOFT_CLIENT_ID
    - MICROSOFT_CLIENT_SECRET
    - RAILS_INBOUND_EMAIL_PASSWORD
  clear:
    # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
    # When you start using multiple servers, you should split out job processing to a dedicated machine.
    SOLID_QUEUE_IN_PUMA: true

    # Set number of processes dedicated to Solid Queue (default: 1)
    # JOB_CONCURRENCY: 3

    # Set number of cores available to the application on each server (default: 1).
    # WEB_CONCURRENCY: 2

    # Match this to any external database server to configure Active Record correctly
    # Use crm-db for a db accessory server on same machine via local kamal docker network.
    # DB_HOST: 192.168.0.2

    # Log everything from Rails
    # RAILS_LOG_LEVEL: debug

    # Email files directory (synced from local)
    EMAILS_DIR: /emails

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "crm_storage:/rails/storage"
  - "/root/crm-emails:/emails:ro"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets


# Configure the image builder.
builder:
  arch: arm64  # Graviton (ARM64)

# SSH as root
ssh:
  user: root

# Accessory services
accessories:
  postfix:
    image: 225656797743.dkr.ecr.eu-west-1.amazonaws.com/crm-postfix
    host: 52.30.167.17
    port: "25:25"
    env:
      clear:
        RAILS_INBOUND_HOST: crm-web:3000
      secret:
        - RAILS_INBOUND_EMAIL_PASSWORD
    directories:
      - postfix_spool:/var/spool/postfix
